-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 10:43:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistematienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistematienda` ;

-- -----------------------------------------------------
-- Schema sistematienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistematienda` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistematienda` ;

-- -----------------------------------------------------
-- Table `sistematienda`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`categorias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`clientes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(40) NOT NULL,
  `Direccion` VARCHAR(40) NOT NULL,
  `Colonia` VARCHAR(40) NOT NULL,
  `Municipio` VARCHAR(40) NOT NULL,
  `Estado` VARCHAR(40) NOT NULL,
  `CodigoPostal` VARCHAR(40) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Activo` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`ventas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `iva` DECIMAL(10,2) NOT NULL,
  `sutotal` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `Activo` DOUBLE NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sistematienda`.`clientes` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_idCliente` ON `sistematienda`.`ventas` (`idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistematienda`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`productos` (
  `Codigo` VARCHAR(30) NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `VentaPorUnidad` TINYINT(1) NOT NULL,
  `VentaAGranel` TINYINT(1) NOT NULL,
  `VentaPorPaquete` TINYINT(1) NOT NULL,
  `PrecioCosto` DECIMAL(10,2) NOT NULL,
  `Ganancia` DECIMAL(10,2) NOT NULL,
  `precioVenta` DECIMAL(10,2) NOT NULL,
  `Activo` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Categoria` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `fk_Categoria`
    FOREIGN KEY (`Categoria`)
    REFERENCES `sistematienda`.`categorias` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Codigo` ON `sistematienda`.`productos` (`Codigo` ASC) VISIBLE;

CREATE INDEX `fk_Categoria` ON `sistematienda`.`productos` (`Categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistematienda`.`detalles_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`detalles_venta` (
  `idOrden` INT NOT NULL,
  `idProducto` VARCHAR(30) NOT NULL,
  `PrecioUnitario` DECIMAL(10,2) NOT NULL,
  `Cantidad` DECIMAL(10,2) NOT NULL,
  CONSTRAINT `fk_idOrden`
    FOREIGN KEY (`idOrden`)
    REFERENCES `sistematienda`.`ventas` (`Id`),
  CONSTRAINT `fk_idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `sistematienda`.`productos` (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_idOrden` ON `sistematienda`.`detalles_venta` (`idOrden` ASC) VISIBLE;

CREATE INDEX `fk_idProducto` ON `sistematienda`.`detalles_venta` (`idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistematienda`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `CONTRASENIA` LONGTEXT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `usuario` ON `sistematienda`.`usuarios` (`usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistematienda`.`permisocajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`permisocajeros` (
  `IdUsuario` INT NOT NULL,
  `Agregar_Usuarios` TINYINT(1) NOT NULL,
  `Editar_Usuarios` TINYINT(1) NOT NULL,
  `Eliminar_Usuarios` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Permisos_Cajeros`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `sistematienda`.`usuarios` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`permisoclientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`permisoclientes` (
  `IdUsuario` INT NOT NULL,
  `Agregar_Clientes` TINYINT(1) NOT NULL,
  `Editar_Clientes` TINYINT(1) NOT NULL,
  `Eliminar_Clientes` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Permisos_Clientes`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `sistematienda`.`usuarios` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`permisoproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`permisoproductos` (
  `IdUsuario` INT NOT NULL,
  `Agregar_Productos` TINYINT(1) NOT NULL,
  `Editar_Productos` TINYINT(1) NOT NULL,
  `Eliminar_Productos` TINYINT(1) NOT NULL,
  `Crear_Categorias` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Permisos_Productos`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `sistematienda`.`usuarios` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`permisoproveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`permisoproveedores` (
  `IdUsuario` INT NOT NULL,
  `Agregar_Proveedores` TINYINT(1) NOT NULL,
  `Editar_Proveedores` TINYINT(1) NOT NULL,
  `Eliminar_Proveedores` TINYINT(1) NOT NULL,
  `Generar_Facturas` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Permisos_Proveedores`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `sistematienda`.`usuarios` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`permisoventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`permisoventas` (
  `IdUsuario` INT NOT NULL,
  `Registrar_Entradas_De_Dinero` TINYINT(1) NOT NULL,
  `Registrar_Salidas_De_Dinero` TINYINT(1) NOT NULL,
  `Cancelar_compras` TINYINT(1) NOT NULL,
  `Eliminar_Articulos` TINYINT(1) NOT NULL,
  `Generar_facturas` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `FK_Permisos_Ventas`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `sistematienda`.`usuarios` (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistematienda`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`proveedores` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Proveedor` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` LONGTEXT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `Activo` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

select * from proveedores;
-- -----------------------------------------------------
-- Table `sistematienda`.`usuariosprueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematienda`.`usuariosprueba` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(20) NOT NULL,
  `contrasenia` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `sistematienda` ;

-- -----------------------------------------------------
-- procedure spBorradoLogico
-- -----------------------------------------------------

DELIMITER $$
USE `sistematienda`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `spBorradoLogico`(In _Clave int, Out Estatus int)
BEGIN
	if((select count(*) from productos where clave = clave)=1 )then
		update productos
        set estatus = 0        
        where clave = _Clave;    	
	end if;
END$$
DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




use sistematienda;
select * from usuarios;
insert into usuarios values(1,'admin',123,'juan',1);

INSERT INTO usuarios values(2,'admin2',sha2('123',256),'Jovany',2);


INSERT INTO usuarios(usuario,contrasenia,Nombre,Activo) 
                    VALUES ('jovany',sha2('123',256),'govany',1);

                    INSERT INTO permisoventas(IdUsuario, Registrar_Entradas_De_Dinero, Registrar_Salidas_De_Dinero, Cancelar_compras,
                    Eliminar_Articulos, Generar_facturas)VALUES
                    (last_insert_id(), true, true, true, true, true);

                    INSERT INTO permisoproveedores(IdUsuario, Agregar_Proveedores, Editar_Proveedores, Eliminar_Proveedores, Generar_Facturas)
                        VALUES(last_insert_id(), true, true, true, true);

                    INSERT INTO permisoproductos(IdUsuario, Agregar_Productos, Editar_Productos, Eliminar_Productos, Crear_Categorias)
                        VALUES(last_insert_id(), true, true, true, true);

                    INSERT INTO permisoclientes(IdUsuario, Agregar_Clientes, Editar_Clientes, Eliminar_Clientes)
                        VALUES(last_insert_id(), true, true, true);

                    INSERT INTO permisocajeros(IdUsuario, Agregar_Usuarios, Editar_Usuarios, Eliminar_Usuarios)
                        VALUES(last_insert_id(), true, true, true);
                    SELECT last_insert_id();
                    